"use client";

import {
  Check,
  Copy,
  Download,
  ExternalLink,
  Film,
  Image as ImageIcon,
  Loader2,
  Search,
  Trash2,
  Upload,
} from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

interface MediaItem {
  id: string;
  userId: string;
  url: string;
  name: string;
  mimeType: string;
  source: "upload" | "generated";
  prompt?: string | null;
  createdAt: string;
}

export default function MediaLibraryPage() {
  const [media, setMedia] = useState<MediaItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeTab, setActiveTab] = useState<"all" | "upload" | "generated">("all");
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const fetchMedia = useCallback(async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/media");
      if (res.ok) {
        const data = await res.json();
        setMedia(data.media || []);
      } else {
        toast.error("Failed to load media library");
      }
    } catch {
      toast.error("Network error while fetching media");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMedia();
  }, [fetchMedia]);

  const handleCopyUrl = (url: string, id: string) => {
    navigator.clipboard.writeText(url);
    setCopiedId(id);
    toast.success("Image URL copied to clipboard!");
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDelete = async (id: string) => {
    try {
      setDeletingId(id);
      const res = await fetch(`/api/media?id=${id}`, { method: "DELETE" });
      if (res.ok) {
        setMedia((prev) => prev.filter((item) => item.id !== id));
        toast.success("Media deleted from library");
      } else {
        toast.error("Failed to delete media item");
      }
    } catch {
      toast.error("Error deleting media");
    } finally {
      setDeletingId(null);
    }
  };

  const filteredMedia = media.filter((item) => {
    const matchesTab = activeTab === "all" || item.source === activeTab;
    const matchesSearch =
      !searchQuery.trim() ||
      item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (item.prompt && item.prompt.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesTab && matchesSearch;
  });

  return (
    <div className="flex flex-col grow h-full overflow-y-auto bg-background p-4 sm:p-6 md:p-8 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/60 pb-5">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <ImageIcon className="size-6 text-primary" />
            Media Library
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Access all images you've uploaded and images generated by Etles agents.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-xs px-3 py-1 font-medium">
            {media.length} Total Items
          </Badge>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4">
        <Tabs
          defaultValue="all"
          value={activeTab}
          onValueChange={(v) => setActiveTab(v as any)}
          className="w-full sm:w-auto"
        >
          <TabsList className="grid w-full grid-cols-3 sm:w-auto">
            <TabsTrigger value="all">All</TabsTrigger>
            <TabsTrigger value="upload" className="gap-1.5">
              <Upload className="size-3.5" /> Uploads
            </TabsTrigger>
            <TabsTrigger value="generated" className="gap-1.5">
              <ImageIcon className="size-3.5" /> Generated
            </TabsTrigger>
          </TabsList>
        </Tabs>

        <div className="relative w-full sm:w-72">
          <Search className="absolute left-2.5 top-2.5 size-4 text-muted-foreground" />
          <Input
            placeholder="Search media or prompt..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 h-9"
          />
        </div>
      </div>

      {/* Grid */}
      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="size-8 animate-spin text-primary" />
        </div>
      ) : filteredMedia.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center border border-dashed rounded-xl p-8 bg-card/30">
          <ImageIcon className="size-12 text-muted-foreground/50 mb-3" />
          <h3 className="text-lg font-semibold">No media found</h3>
          <p className="text-sm text-muted-foreground max-w-sm mt-1">
            {searchQuery
              ? "No images match your search criteria."
              : "Upload images in chat or ask an agent to generate images to populate your library."}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {filteredMedia.map((item) => (
            <Card
              key={item.id}
              className="group overflow-hidden flex flex-col justify-between border-border/70 shadow-xs hover:shadow-md transition-all"
            >
              <div className="relative aspect-video w-full bg-muted overflow-hidden">
                <Image
                  src={item.url}
                  alt={item.name}
                  fill
                  className="object-cover transition-transform group-hover:scale-105"
                  sizes="(max-width: 768px) 100vw, 25vw"
                />
                <div className="absolute top-2 left-2">
                  <Badge
                    variant={item.source === "generated" ? "default" : "secondary"}
                    className="text-[10px] uppercase font-semibold px-2 py-0.5 shadow-sm"
                  >
                    {item.source === "generated" ? (
                      <span className="flex items-center gap-1">
                        <ImageIcon className="size-3" /> Generated
                      </span>
                    ) : (
                      <span className="flex items-center gap-1">
                        <Upload className="size-3" /> Uploaded
                      </span>
                    )}
                  </Badge>
                </div>
              </div>

              <CardHeader className="p-3 pb-1">
                <CardTitle className="text-xs font-semibold truncate" title={item.name}>
                  {item.name}
                </CardTitle>
                {item.prompt ? (
                  <CardDescription className="text-[11px] line-clamp-2 mt-0.5" title={item.prompt}>
                    "{item.prompt}"
                  </CardDescription>
                ) : null}
              </CardHeader>

              <CardFooter className="p-3 pt-2 flex items-center justify-between border-t border-border/40 mt-auto">
                <span className="text-[10px] text-muted-foreground">
                  {new Date(item.createdAt).toLocaleDateString()}
                </span>
                <div className="flex items-center gap-1">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="size-7"
                    title="Copy URL"
                    onClick={() => handleCopyUrl(item.url, item.id)}
                  >
                    {copiedId === item.id ? (
                      <Check className="size-3.5 text-green-500" />
                    ) : (
                      <Copy className="size-3.5" />
                    )}
                  </Button>
                  <a href={item.url} target="_blank" rel="noreferrer" download>
                    <Button variant="ghost" size="icon" className="size-7" title="Open / Download">
                      <ExternalLink className="size-3.5" />
                    </Button>
                  </a>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="size-7 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                    title="Delete"
                    disabled={deletingId === item.id}
                    onClick={() => handleDelete(item.id)}
                  >
                    {deletingId === item.id ? (
                      <Loader2 className="size-3.5 animate-spin" />
                    ) : (
                      <Trash2 className="size-3.5" />
                    )}
                  </Button>
                </div>
              </CardFooter>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
