/**
 * lib/ai/tools/media-library.ts
 *
 * Media Library tool for sub-agents and chat agents.
 * Allows agents to list, search, and recall images/files uploaded by the user
 * or generated by agents during previous sessions.
 */

import { tool } from "ai";
import { z } from "zod";
import { getUserMediaByUserId } from "@/lib/db/queries";

export const listUserMedia = ({ userId }: { userId: string }) =>
  tool({
    description:
      "Search or list the user's media library (uploaded images, documents, and AI-generated images). " +
      "Use this tool when the user asks to find an uploaded image, locate a generated poster, or reference an existing asset.",
    inputSchema: z.object({
      source: z
        .enum(["upload", "generated"])
        .optional()
        .describe("Filter by 'upload' for uploaded files or 'generated' for AI-created images."),
      query: z
        .string()
        .optional()
        .describe("Optional search term to filter media by name or generation prompt."),
    }),
    execute: async ({ source, query }) => {
      try {
        const media = await getUserMediaByUserId({ userId, source });
        let filtered = media;

        if (query?.trim()) {
          const q = query.toLowerCase().trim();
          filtered = media.filter(
            (m) =>
              m.name.toLowerCase().includes(q) ||
              (m.prompt && m.prompt.toLowerCase().includes(q))
          );
        }

        return {
          success: true,
          count: filtered.length,
          media: filtered.map((m) => ({
            id: m.id,
            name: m.name,
            url: m.url,
            source: m.source,
            mimeType: m.mimeType,
            prompt: m.prompt ?? undefined,
            createdAt: m.createdAt.toISOString(),
          })),
        };
      } catch (err: any) {
        return {
          success: false,
          error: err?.message ?? String(err),
        };
      }
    },
  });
